route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#live_web'
            api_url: 'https://hooks.slack.com/services/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'

